# docker-compose.yml
version: "3.8"

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password # Change this to a secure password
      MYSQL_DATABASE: bakeries_db # Change this to your desired database name
      MYSQL_USER: your_user # Change this to your desired username
      MYSQL_PASSWORD: user_password # Change this to a secure user password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
